增加管理员悄悄进服权限
DreamVoid/Chat2QQ pull request #13
Opened 2021-09-11 16:33 UTC by XXY233

2021-09-11 17:19 UTC, DreamVoid requested changes
权限节点用```chat2qq```开头，miraimc开头的权限节点要给miraimc留着，不如改成chat2qq.join.silent和chat2qq.quid.silent，default设为false

2021-09-11 17:29 UTC, DreamVoid approved these changes

2021-09-11 17:37 UTC, DreamVoid reviewed
去掉```!```不就变成“玩家有安静权限则发送消息”吗？这不是和功能相悖吗？

2021-09-11 17:40 UTC, XXY233 commented
> 去掉`!`不就变成“玩家有安静权限则发送消息”吗？这不是和功能相悖吗？

妈耶，太困了脑子都不好使了

2021-09-12 03:21 UTC, DreamVoid approved these changes

2021-09-12 05:47 UTC, DreamVoid commented
你找个时间重新弄一下吧，我搞了maven模块，而且你这没用的commit有点太多了

2021-09-12 08:00 UTC, DreamVoid approved these changes

2021-09-19 09:48 UTC, merged