添加消息处理功能
DreamVoid/Chat2QQ pull request #67
Opened 2023-01-18 08:23 UTC by ApliNi

**新增配置**
```yaml
  # 预处理 %message% 中的消息
  pretreatment:
    # 不使用时请关闭
    enabled: false
    # **使用方法**
    # list:
    #   - 匹配方式: prefix (前缀匹配), 可用处理方式: to_all
    #                                           to_replace
    #             contain (包含), 可用处理方式: to_all
    #                                        to_replace
    #             equal (完全相等), 可用处理方式: to_all
    #             regular (正则匹配), 可用处理方式: to_all
    #                                           to_regular
    #     处理方式: to_all (替换整条消息)
    #             to_replace (替换匹配到的部分)
    #             to_regular (使用正则替换, 可使用正则变量)
    #
    #     是否发送: send (填写 send 配置将取消转发送匹配到的消息, 不需要时请忽略)
    #
    # > 正则的性能较差, 请尽量避免使用很多正则
    # 示例配置, 默认配置了一些可能有用的功能:
    list:

      # 简单的匹配卡片消息
      - prefix: '{"app":"com.tencent.'
        to_all: "[卡片消息]"

#      # 更好的匹配卡片消息, 使用正则解析内容
#      - regular: '\{"app":"com.tencent.miniapp(?:.*)"prompt":"(?:.*?)](.*?)","(?:.*)"desc":"(.*?)","(?:.*)' # miniApp
#        to_regular: "[小程序: $1] $2" # [小程序: 哔哩哔哩] xxxxxxx
#
#      - regular: '\{"app":"com.tencent.structmsg(?:.*)"tag":"(.*?)","title":"(.*?)","(?:.*)' # structMsg
#        to_regular: "[卡片消息: $1] $2" # [卡片消息: 哔哩哔哩] xxxxxxx
```

**预设配置效果图**
![image](https://user-images.githubusercontent.com/59365724/213120260-105e351e-62d8-4693-86d2-caa05049afb0.png)

2023-01-18 12:27 UTC, ApliNi commented
稍等, 我还准备添加运行指令的功能

2023-01-18 13:32 UTC, ApliNi commented
**运行指令**
```yaml
  # 在QQ群中运行指令
  run-command:
    # 不使用时请关闭
    enabled: false
    # 启用此功能的QQ群
    qq-group:
      - 1000001
    # 指令前缀, 可以是多个字符, 比如 "~$"
    prefix: "/"
    # 指令最大长度 (不包括指令前缀)
    command-max-length: 255
    # 是否发送指令的输出, 关闭可提高性能或解决一些兼容性问题
    return: true
    # 等待指令运行多长时间再处理输出 (毫秒), 需要开启 return
    sleep: 500
    # 运行无返回指令的消息
    message-no-out: "运行无返回指令"
    # 设置各组可执行的指令, 改为 `OWNER: []` 即可执行所有指令
    # 消息以设定的指令开头则作为指令运行, 因此可以精确到指令参数
    group:
      OWNER: # 群主
        - 指令
      ADMINISTRATOR: # 管理员
        - 指令
      MEMBER: # 成员 (默认组)
        - 指令
```

2023-01-18 15:03 UTC, DreamVoid requested changes
执行指令不应该是一个聊天插件的工作

2023-01-18 15:19 UTC, ApliNi commented
已修改

2023-01-27 13:08 UTC, DreamVoid requested changes

2023-01-27 13:21 UTC, ApliNi commented on Chat2QQ-Bukkit/src/main/java/me/dreamvoid/chat2qq/bukkit/listener/onGroupMessage.java
> +    public void onGroupMessageReceive(MiraiGroupMessageEvent e) throws InterruptedException {
抱歉我没有检查它, 这是运行指令部分用到的

2023-01-27 13:24 UTC, DreamVoid approved these changes

2023-01-31 05:54 UTC, merged